# Generated by Django 6.0.1 on 2026-02-12 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_business_deleted_at_business_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Obrt', 'verbose_name_plural': 'Obrti'},
        ),
        migrations.AlterModelOptions(
            name='businessowner',
            options={'verbose_name': 'Vlasnik', 'verbose_name_plural': 'Vlasnici'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'verbose_name': 'Dokument', 'verbose_name_plural': 'Dokumenti'},
        ),
        migrations.AlterModelOptions(
            name='inspection',
            options={'verbose_name': 'Inspekcija', 'verbose_name_plural': 'Inspekcije'},
        ),
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Dozvola', 'verbose_name_plural': 'Dozvole'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Vlasnik', 'verbose_name_plural': 'Vlasnici'},
        ),
        migrations.AlterField(
            model_name='business',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresa/Sjedište'),
        ),
        migrations.AlterField(
            model_name='business',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Grad'),
        ),
        migrations.AlterField(
            model_name='business',
            name='date_registered',
            field=models.DateField(verbose_name='Datum registracije'),
        ),
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Vrsta obrta'),
        ),
        migrations.AlterField(
            model_name='business',
            name='legal_form',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zanimanje'),
        ),
        migrations.AlterField(
            model_name='business',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Naziv obrta'),
        ),
        migrations.AlterField(
            model_name='business',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Zabilješke'),
        ),
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='business',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Poštanski broj'),
        ),
        migrations.AlterField(
            model_name='business',
            name='registration_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='Broj rješenja'),
        ),
        migrations.AlterField(
            model_name='business',
            name='status',
            field=models.CharField(choices=[('active', 'Aktivan'), ('inactive', 'Neaktivan'), ('suspended', 'Na čekanju')], default='active', max_length=50),
        ),
        migrations.AlterField(
            model_name='business',
            name='tax_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Porezni id br.'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresa'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Datum i vrijeme unosa'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Ime Vlasnika'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Prezime Vlasnika'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='personal_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='JMBG'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Telefon'),
        ),
    ]
