# Generated by Django 5.0.6 on 2026-02-17 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0008_alter_business_industry_alter_business_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(blank=True, choices=[('trgovina', 'Trgovinska'), ('ugostiteljstvo', 'Ugostiteljska'), ('obrt', 'Obrtnička')], max_length=50, null=True, verbose_name='Vrsta djelatnosti'),
        ),
    ]
