# Generated by Django 5.0.6 on 2026-02-19 12:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_business_industry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Profesija',
                'verbose_name_plural': 'Profesije',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='business',
            name='date_registered',
            field=models.DateField(verbose_name='Datum rješenja/registracije'),
        ),
        migrations.AddField(
            model_name='business',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='registry.profession', verbose_name='Profesija'),
        ),
    ]
