# Generated by Django 5.0.6 on 2026-02-19 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0010_profession_alter_business_date_registered_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='legal_form',
        ),
    ]
