# Generated by Django 5.0.6 on 2026-02-19 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0011_remove_business_legal_form'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profession',
            options={'ordering': ['code'], 'verbose_name': 'Zanimanje', 'verbose_name_plural': 'Zanimanja'},
        ),
        migrations.AlterField(
            model_name='business',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='businesses', to='registry.profession', verbose_name='Zanimanje'),
        ),
    ]
