# Generated by Django 5.0.6 on 2026-03-04 07:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0012_alter_profession_options_alter_business_profession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitycode',
            options={'ordering': ['code'], 'verbose_name': 'Djelatnost', 'verbose_name_plural': 'Djelatnosti'},
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='businesses', to='registry.owner', verbose_name='Vlasnik'),
        ),
        migrations.AlterField(
            model_name='businessowner',
            name='ownership_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Udio vlasništva'),
        ),
        migrations.AlterField(
            model_name='license',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum isteka'),
        ),
        migrations.AlterField(
            model_name='license',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum izdavanja'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_number',
            field=models.CharField(max_length=100, verbose_name='Broj dozvole'),
        ),
        migrations.AlterField(
            model_name='license',
            name='license_type',
            field=models.CharField(max_length=150, verbose_name='Vrsta dozvole'),
        ),
        migrations.CreateModel(
            name='BusinessHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_registration_number', models.CharField(max_length=100)),
                ('old_address', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='registry.business')),
                ('changed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
