# Generated by Django 5.0.6 on 2026-03-05 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0013_alter_activitycode_options_alter_businessowner_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businesshistory',
            name='old_address',
        ),
        migrations.RemoveField(
            model_name='businesshistory',
            name='old_registration_number',
        ),
        migrations.AddField(
            model_name='businesshistory',
            name='reason',
            field=models.TextField(default='System generated'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businesshistory',
            name='snapshot',
            field=models.JSONField(default='System generated'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='businesshistory',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='registry.business'),
        ),
    ]
