# Generated by Django 5.0.6 on 2026-03-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0014_remove_businesshistory_old_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Obrt', 'verbose_name_plural': 'Poslovanja'},
        ),
        migrations.AddField(
            model_name='business',
            name='obrt_type',
            field=models.CharField(blank=True, choices=[('obrt', 'Obrt'), ('stari_zanat', 'Stari zanat'), ('domaca_radinost', 'Domaća radinost'), ('srodna_djelatnost', 'Srodna djelatnost')], max_length=50, null=True, verbose_name='Vrsta obrta'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspection_date',
            field=models.DateField(verbose_name='Datum'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='inspector_name',
            field=models.CharField(max_length=150, verbose_name='Inspektor'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='remarks',
            field=models.TextField(blank=True, null=True, verbose_name='Komentar'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='result',
            field=models.CharField(choices=[('passed', 'Prošao'), ('failed', 'Nije Prošao')], max_length=50, verbose_name='Nalaz'),
        ),
        migrations.DeleteModel(
            name='BusinessHistory',
        ),
    ]
