# Generated by Django 5.0.6 on 2026-03-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0015_alter_business_options_business_obrt_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='ending_registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Broj rješenja o prestanku'),
        ),
    ]
