# Generated by Django 5.0.6 on 2026-05-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0017_alter_business_industry_alter_inspection_result_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='is_foreign_trade',
            field=models.BooleanField(default=False, verbose_name='Obavlja obrt u vanjskotrgovinskom poslovanju'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='document_number',
            field=models.CharField(max_length=100, verbose_name='Broj rješenja'),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='result',
            field=models.CharField(choices=[('compliant', 'Ispunjava uslove'), ('non_compliant', 'Ne ispunjava uslove')], max_length=50, verbose_name='Mišljenje'),
        ),
    ]
