# Generated by Django 5.0.6 on 2026-05-06 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0018_business_is_foreign_trade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='sex',
            field=models.CharField(blank=True, choices=[('M', 'Muški'), ('F', 'Ženski')], max_length=1, null=True, verbose_name='Spol'),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('osnovno', 'Osnovno'), ('dopunsko', 'Dopunsko'), ('dodatno', 'Dodatno'), ('paušalno', 'Paušalno')], default='osnovno', max_length=20, verbose_name='Način obavljanja'),
        ),
    ]
