from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.pdfgen import canvas
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import Table, TableStyle, Paragraph
from reportlab.lib import colors
from io import BytesIO
from django.http import HttpResponse
from django.utils.timezone import now


def businesses_to_pdf(queryset, user):
    buffer = BytesIO()
    pdf = canvas.Canvas(buffer, pagesize=A4)
    width, height = A4

    styles = getSampleStyleSheet()

    # Title
    pdf.setFont("Helvetica-Bold", 14)
    pdf.drawString(2 * cm, height - 2 * cm, "Business Registry Report")

    pdf.setFont("Helvetica", 9)
    pdf.drawString(
        2 * cm,
        height - 2.7 * cm,
        f"Generated by: {user.username} | {now().strftime('%Y-%m-%d %H:%M')}"
    )

    # Table data
    data = [
        ["Name", "Reg. No", "City", "Status"]
    ]

    for b in queryset:
        data.append([
            b.name,
            b.registration_number,
            b.city,
            b.status,
        ])

    table = Table(data, colWidths=[6 * cm, 4 * cm, 3 * cm, 3 * cm])
    table.setStyle(TableStyle([
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
        ("FONT", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONT", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (1, 1), (-1, -1), "LEFT"),
    ]))

    table.wrapOn(pdf, width, height)
    table.drawOn(pdf, 2 * cm, height - 5 * cm - 20 * len(data))

    pdf.showPage()
    pdf.save()

    buffer.seek(0)
    response = HttpResponse(buffer, content_type="application/pdf")
    response["Content-Disposition"] = "inline; filename=businesses.pdf"
    return response

