from reportlab.lib import colors
from reportlab.platypus import HRFlowable
from io import BytesIO
import os
from django.http import HttpResponse
from django.utils.timezone import now
from django.utils.text import capfirst
from django.conf import settings

from reportlab.platypus import (
    SimpleDocTemplate,
    Table,
    TableStyle,
    Paragraph,
    Spacer,
    Image,
)
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.lib.pagesizes import A4, landscape
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.pdfbase import pdfmetrics


def queryset_to_pdf(queryset, user, fields, title="", logo_path=None, order_by=None):
    """
    Generic PDF generator for any model queryset.
    """
    buffer = BytesIO()
    page_size = landscape(A4)

    # =====================================================
    # REGISTER UNICODE FONTS
    # =====================================================
    font_regular_path = os.path.join(settings.BASE_DIR, "fonts", "DejaVuSans.ttf")
    font_bold_path = os.path.join(settings.BASE_DIR, "fonts", "DejaVuSans-Bold.ttf")

    pdfmetrics.registerFont(TTFont("DejaVuSans", font_regular_path))
    pdfmetrics.registerFont(TTFont("DejaVuSans-Bold", font_bold_path))

    # =====================================================
    # DOCUMENT SETUP
    # =====================================================
    doc = SimpleDocTemplate(
        buffer,
        pagesize=page_size,
        rightMargin=2 * cm,
        leftMargin=2 * cm,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
    )

    elements = []
    styles = getSampleStyleSheet()

    # Table styles
    table_header_style = styles["Normal"].clone("table_header")
    table_header_style.fontName = "DejaVuSans-Bold"
    table_header_style.fontSize = 9
    table_header_style.leading = 11

    table_cell_style = styles["Normal"].clone("table_cell")
    table_cell_style.fontName = "DejaVuSans"
    table_cell_style.fontSize = 9
    table_cell_style.leading = 11

    styles["Normal"].fontName = "DejaVuSans"
    styles["Heading1"].fontName = "DejaVuSans-Bold"
    styles["Heading2"].fontName = "DejaVuSans-Bold"

    # =====================================================
    # HEADER WITH LOGO
    # =====================================================
    header_elements = []

    if logo_path and os.path.exists(logo_path):
        logo = Image(logo_path)
        max_width = 3 * cm
        max_height = 3 * cm

        img_width, img_height = logo.imageWidth, logo.imageHeight
        ratio = min(max_width / img_width, max_height / img_height)

        logo.drawWidth = img_width * ratio
        logo.drawHeight = img_height * ratio
        logo.hAlign = 'LEFT'
    else:
        logo = Paragraph("", styles["Normal"])  # empty placeholder if no logo

    # Title and user info
    title_info = [
        Paragraph(title, styles["Heading1"]),
        Spacer(1, 0.1*cm),
        Paragraph(f"Generated by: {user.username}", styles["Normal"]),
        Paragraph(f"Date and time: {now().strftime('%d-%m-%Y %H:%M')}", styles["Normal"]),
    ]

    # Create a 2-column table: logo left, info right
    header_table = Table(
        [[logo, title_info]],
        colWidths=[3.5*cm, 18*cm]  # adjust the right column width as needed
    )
    header_table.setStyle(TableStyle([
        ("VALIGN", (0,0), (-1,-1), "TOP"),
        ("LEFTPADDING", (0,0), (-1,-1), 0),
        ("RIGHTPADDING", (0,0), (-1,-1), 0),
        ("TOPPADDING", (0,0), (-1,-1), 0),
        ("BOTTOMPADDING", (0,0), (-1,-1), 0),
    ]))
    
    elements.append(header_table)
    elements.append(HRFlowable(width="100%", thickness=1, color=colors.grey))
    elements.append(Spacer(1, 0.5*cm))

    # =====================================================
    # TABLE DATA
    # =====================================================
    model = queryset.model
    headers = [
        Paragraph(capfirst(model._meta.get_field(field).verbose_name), table_header_style)
        for field in fields
    ]
    data = [headers]

    for obj in queryset:
        row = []
        for field in fields:
            display_method = f"get_{field}_display"
            if hasattr(obj, display_method):
                value = getattr(obj, display_method)()
            else:
                value = getattr(obj, field)

            if value is None:
                value = ""
            elif isinstance(value, bool):
                value = "Yes" if value else "No"

            row.append(Paragraph(str(value), table_cell_style))
        data.append(row)

    # =====================================================
    # TABLE CREATION
    # =====================================================
    col_widths = [6*cm] + [3*cm]*(len(fields)-1)
    table = Table(data, repeatRows=1, colWidths=col_widths)
    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.lightgrey),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
            ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
            ("ALIGN", (5, 1), (6, -1), "CENTER"),
            ("LEFTPADDING", (0, 0), (-1, -1), 4),
            ("RIGHTPADDING", (0, 0), (-1, -1), 4),
            ("TOPPADDING", (0, 0), (-1, -1), 4),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ])
    )
    elements.append(table)

    # =====================================================
    # PAGE NUMBERS
    # =====================================================
    def add_page_number(canvas, doc):
        canvas.setFont("DejaVuSans", 8)
        canvas.drawRightString(
            page_size[0] - 2 * cm,
            1.5 * cm,
            f"Page {doc.page}",
        )

    doc.build(elements, onFirstPage=add_page_number, onLaterPages=add_page_number)

    buffer.seek(0)
    response = HttpResponse(buffer, content_type="application/pdf")
    response["Content-Disposition"] = f"inline; filename={model.__name__}_report.pdf"
    return response