# Generated by Django 6.0.1 on 2026-02-12 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_alter_business_options_alter_businessowner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='activity_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Šifra djelatnosti'),
        ),
        migrations.AddField(
            model_name='business',
            name='assigned_clerk',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'clerk'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_businesses', to=settings.AUTH_USER_MODEL, verbose_name='Dodijeljeni službenik'),
        ),
        migrations.AddField(
            model_name='business',
            name='bank_account',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Broj računa'),
        ),
        migrations.AddField(
            model_name='business',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum prestanka rada'),
        ),
        migrations.AddField(
            model_name='business',
            name='internal_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Interne napomene'),
        ),
        migrations.AddField(
            model_name='business',
            name='is_vat_registered',
            field=models.BooleanField(default=False, verbose_name='PDV obveznik'),
        ),
        migrations.AddField(
            model_name='business',
            name='number_of_employees',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Broj zaposlenih'),
        ),
        migrations.AddField(
            model_name='business',
            name='secondary_activity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dodatna djelatnost'),
        ),
        migrations.AddField(
            model_name='business',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='Datum početka rada'),
        ),
    ]
