# Generated by Django 6.0.1 on 2026-02-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0005_business_activity_code_business_assigned_clerk_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.RemoveField(
            model_name='business',
            name='secondary_activity',
        ),
        migrations.AddField(
            model_name='business',
            name='secondary_activities',
            field=models.ManyToManyField(blank=True, related_name='secondary_businesses', to='registry.activitycode', verbose_name='Dodatne djelatnosti'),
        ),
        migrations.AlterField(
            model_name='business',
            name='activity_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_businesses', to='registry.activitycode', verbose_name='Glavna djelatnost'),
        ),
    ]
