# Generated by Django 5.0.6 on 2026-02-16 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0006_activitycode_remove_business_secondary_activity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_type',
            field=models.CharField(choices=[('osnovno', 'Osnovno'), ('dopunsko', 'Dopunsko'), ('dodatno', 'Dodatno')], default='osnovno', max_length=20, verbose_name='Način obavljanja'),
        ),
    ]
