# Generated by Django 5.0.6 on 2026-02-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0007_business_business_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='industry',
            field=models.CharField(blank=True, choices=[('trgovina', 'Trgovina'), ('ugostiteljstvo', 'Ugostiteljstvo'), ('proizvodnja', 'Proizvodnja')], max_length=50, null=True, verbose_name='Vrsta djelatnosti'),
        ),
        migrations.AlterField(
            model_name='business',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Brisan iz Registra'),
        ),
        migrations.AlterField(
            model_name='license',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Brisan iz Registra'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Brisan iz Registra'),
        ),
    ]
