# Generated by Django 5.0.6 on 2026-02-19 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0009_alter_business_industry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='date_registered',
            field=models.DateField(verbose_name='Datum rješenja/registracije'),
        ),
        migrations.CreateModel(
            name='Profession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Šifra')),
                ('name', models.CharField(max_length=255, verbose_name='Naziv zanimanja')),
            ],
            options={
                'verbose_name': 'Zanimanje',
                'verbose_name_plural': 'Zanimanja',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['name'], name='registry_pr_name_316906_idx')],
            },
        ),
        migrations.AlterField(
            model_name='business',
            name='legal_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='registry.profession', verbose_name='Zanimanje'),
        ),
    ]
